{
 "title": "Node statistics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up,instance)" } },
   {
    "name": "net_interface",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{instance=\"$instance\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\",device=\"$net_interface\"}[1m])",
     "legendFormat": "{{device}} send"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\",device=\"$net_interface\"}[1m])",
     "legendFormat": "{{device}} recive"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "load avg (1m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "load avg (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "load avg (15m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"} - node_memory_Buffers_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\", fstype!=\"ramfs\", fstype!=\"tmpfs\"} - node_filesystem_avail_bytes{instance=\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$instance\", fstype!=\"ramfs\",fstype!=\"tmpfs\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}