global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "prometheus_master"
    scrape_interval: 5s
    static_configs:
      - targets:
           ["localhost:9090"]
  - job_name: "server"
    scrape_interval: 5s
    static_configs:
      - targets:
          ["node_exporter:9100"]
  - job_name: "nas"
    scrape_interval: 5s
    static_configs:
      - targets:
          ["192.168.2.4:9100"]
